FROM golang:alpine3.13 as build

WORKDIR /app

COPY . .

RUN go build

FROM scratch

WORKDIR /root/

ENV REQUEST_ORIGIN http://localhost:5000

COPY --from=build ./app/server ./server

CMD ./server

EXPOSE 8080