FROM node:16-alpine
# set working directory

WORKDIR /app

# copy package.json to the working directory
COPY package.json /app

# install dependencies
RUN npm i

# copy app files to the working directory
COPY . /app

# install dependencies and build app && create the appuser
RUN npm run build && \
    npm install -g serve && \
    addgroup -S appgroup && \
    adduser -S appuser -G appgroup

USER appuser
CMD ["npx", "serve", "-s", "-l", "3000", "build"]

# expose port
EXPOSE 3000