FROM node:16.20.0-slim as app

WORKDIR /app

COPY . .

RUN npm install && npm run build

FROM node:16.20.0-slim

WORKDIR /root/

RUN apk add --update nodejs npm && npm install -g serve

COPY --from=app ./app/build ./build

ENV REACT_APP_BACKEND_URL http://localhost:8080/

CMD ["npx", "serve", "-s", "-l", "5000", "build"] 

EXPOSE 5000