FROM ubuntu:latest

#set working directory
WORKDIR /app

#copy app to image
COPY . /app

#install go
RUN apt-get update && apt-get install -y wget gcc && rm -rf /usr/local/go && wget -c https://golang.org/dl/go1.16.3.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz

#set path
ENV PATH /usr/local/go/bin:$PATH

#set env
ENV REQUEST_ORIGIN http://localhost:5000

# build app
RUN go build

# test app
RUN go test

# create the appuser
RUN useradd -m appuser

# change the owner of current dir to appuser
RUN chown appuser .

# now we can change the user
USER appuser

#run server
CMD ./server

#expose port
EXPOSE 8080