FROM node:16-alpine
# set working directory
ENV REACT_APP_BACKEND_URL http://localhost:8080/

WORKDIR /app

# copy package.json to the working directory
COPY package.json /app

# install dependencies
RUN npm i

# copy app files to the working directory
COPY . /app

# install dependencies and build app
RUN npm run build && npm install -g serve

# create the appuser
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# now we can change the user
USER appuser

CMD ["npx", "serve", "-s", "-l", "5000", "build"]

# expose port
EXPOSE 5000