version: '3.8'

services:

    web-server:
      image: devopsdockeruh/simple-web-service
      build: .
      volumes:
        - ./text.log:/usr/src/app/text.log
      ports: 
          - 8080:8080
      container_name: web-server-secret
      command: ["server"]