version: '3.9'

services:

    frontend:
      container_name: frontend
      image: frontend
      build: ./frontend
      ports: 
          - 5000:5000
    backend:
      container_name: backend
      image: backend
      build: ./backend
      ports:
          - 8080:8080
      environment: 
        REDIS_HOST: redis
      depends_on: 
          - redis
    redis:
      container_name: redis-cache
      image: redis
      restart: unless-stopped