FROM node:16.20.0-slim

WORKDIR /app

COPY . .

ENV REACT_APP_BACKEND_URL http://localhost:8080/

RUN npm install && npm run build && npm install -g serve

CMD ["npx", "serve", "-s", "-l", "5000", "build"]

EXPOSE 5000