FROM ubuntu:latest

#set working directory
WORKDIR /app
#copy app to image
COPY . /app
#install go
RUN apt-get update && \
    apt-get install -y wget gcc && \
    rm -rf /usr/local/go && wget -c https://golang.org/dl/go1.16.3.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz && \
    # remove useless files from the current layer
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/lib/apt/lists.d/* && \
    apt-get autoremove && \
    apt-get clean && \
    apt-get autoclean
#set path
ENV PATH /usr/local/go/bin:$PATH
#set env
ENV REQUEST_ORIGIN http://localhost:5000
# build app && create the appuser
RUN go build && \
    go test && useradd -m appuser && \
    chown appuser . && \
    apt-get purge -y --auto-remove wget && \
    rm -rf /var/lib/apt/lists/*
# now we can change the user
USER appuser
#run server
CMD ./server
#expose port
EXPOSE 8080